"""Migración inicial y creación de tablas

Revision ID: d304867f4399
Revises:
Create Date: 2026-03-18 20:45:11.226752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d304867f4399"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sanciones_id_sancion"), table_name="sanciones")
    op.drop_table("sanciones")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sanciones",
        sa.Column("id_sancion", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("fecha_inicio", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("dias_sancion", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "motivo", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("id_usuario", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id_prestamo", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "fecha_creacion",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "fecha_edicion",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id_usuario_crea", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id_usuario_edita", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["id_prestamo"],
            ["prestamos.id_prestamo"],
            name=op.f("sanciones_id_prestamo_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuarios.id_usuario"],
            name=op.f("sanciones_id_usuario_fkey"),
        ),
        sa.PrimaryKeyConstraint("id_sancion", name=op.f("sanciones_pkey")),
    )
    op.create_index(
        op.f("ix_sanciones_id_sancion"), "sanciones", ["id_sancion"], unique=False
    )
    # ### end Alembic commands ###
